### PR TITLE
Fix input handling around `-P` flag with the DNS module, Resolves #746

### LINKED ISSUE #746: Problem with -P option in DNS module
> Notice: Please don't file a bug report for questions on how to use ZMap, etc. Check out our [Resources](https://github.com/zmap/zmap/tree/main#resources) section for FAQ and feel free to chime in on [Github Discussions](https://github.com/zmap/zmap/discussions) if you're still unclear and we'll be happy to assist!

**Describe the bug**
I encountered an issue when using the -P option with the DNS module in zmap. It seems that the option is not applicable for the DNS module, but it gives the following error message:
```
[WARN] blocklist: ZMap is currently using the default blocklist located at /etc/zmap/blocklist.conf. By default, this blocklist excludes locally scoped networks (e.g., 10.0.0.0/8, 127.0.0.1/8, and 192.168.0.0/16). If you are trying to scan local networks, you can change the default blocklist by editing the default ZMap configuration at /etc/zmap/blocklist.conf. If you have modified the default blocklist, you can ignore this message.
[FATAL] dns: Invalid probe args. Format: "A,google.com" or "A,google.com;A,example.com"
```

**CLI Arguments**
Please paste your ZMap invocation below

```
zmap -p 53 -P 10 --probe-module=dns --probe-args="A,example.com" -B 400K --output-filter="" -O json -o logfile.json 
```

**Expected behavior**
The -P option should not be applicable for the DNS module, or there should be proper documentation indicating that it is not supported.

**Environment:**
 - OS:  Ubuntu 22.04

### PR DESCRIPTION
**Pull request by phillip-stephens**
## Context available in Issue #746 

- [x] added new parsing to identify how many DNS questions in `--probe-args` the user passed in based on count of semi-colons
- [x] error out if user uses a value for `-P` that isn't a multiple of the number of DNS questions
    - [x] Ex: `-P 4 --probe-args="A,google.com;AAAA,cloudflare.com"` is acceptable since 4 probes is a multiple of 2 DNS questions
 
Note: The `--dedup` uses the scanned host's source IP address to de-duplicate responses. This means that if you send 4 probes and 2 DNS queries to `8.8.8.8` (2 probes per question), then ZMap only marks 1 of the 4 as a "application success". This seems mis-leading, but perhaps this is just how ZMap is designed? The de-dupeing is baked into `recv.c`, so it's not probe-module specific.

## Tests

- [x] Tested with no probe args - ``
- [x] Tested with 1 arg - `A,google.com`
- [x] Tested with 1 arg, leading semicolon - `;A,google.com`
- [x] Tested with 1 arg, trailing semicolon - `A,google.com;`
- [x] Tested with 2 arg - `A,google.com;AAAA,yahoo.com`
- [x] Tested with bad domain - `A,`

Notice how there's 2 responses in the `logfile.json`, and that the `app hitrate` being printed maxes out at 50%
```shell
pstephens@scratch-04-a:~/zmap-rsync$ sudo ./src/zmap -p 53 --probe-module=dns -O json -o logfile.json -P 2 1.1.1.1 --sender-threads=1 --probe-args="A,yahoo.com" --output-fields=* -c 3
Dec 19 19:08:37.852 [INFO] dedup: Response deduplication method is full
Dec 19 19:08:37.852 [INFO] filter: No output filter provided. ZMap will output all results, including duplicate and non-successful responses (e.g., RST and ICMP packets). If you want a filter similar to ZMap's default behavior, you can set an output filter similar to the following: --output-filter="success=1 && repeat=0".
Dec 19 19:08:37.907 [INFO] recv: duplicate responses will be passed to the output module
Dec 19 19:08:37.907 [INFO] recv: unsuccessful responses will be passed to the output module
 0:00 2%; sent: 2 done (42 p/s avg); recv: 0 0 p/s (0 p/s avg); app success: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00% app hitrate: 0.00%
 0:00 2%; sent: 2 done (42 p/s avg); recv: 0 0 p/s (0 p/s avg); app success: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00% app hitrate: 0.00%
 0:01 34%; sent: 2 done (42 p/s avg); recv: 2 2 p/s (1 p/s avg); app success: 1 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 100.00% app hitrate: 50.00%
 0:02 67%; sent: 2 done (42 p/s avg); recv: 2 0 p/s (0 p/s avg); app success: 1 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 100.00% app hitrate: 50.00%
 0:03 101%; sent: 2 done (42 p/s avg); recv: 2 0 p/s (0 p/s avg); app success: 1 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 100.00% app hitrate: 50.00%
Dec 19 19:08:41.950 [INFO] zmap: completed
pstephens@scratch-04-a:~/zmap-rsync$ cat logfile.json
{"saddr":"1.1.1.1","saddr_raw":16843009,"daddr":"171.67.71.40","daddr_raw":675759019,"ipid":64826,"ttl":57,"sport":53,"dport":59554,"classification":"dns","success":true,"app_success":true,"udp_len":131,"dns_id":28666,"dns_rd":1,"dns_tc":0,"dns_aa":0,"dns_opcode":0,"dns_qr":1,"dns_rcode":0,"dns_cd":0,"dns_ad":0,"dns_z":0,"dns_ra":1,"dns_qdcount":1,"dns_ancount":6,"dns_nscount":0,"dns_arcount":0,"dns_questions":[{"name":"yahoo.com","qtype":1,"qtype_str":"A","qclass":1}],"dns_answers":[{"name":"yahoo.com","type":1,"type_str":"A","class":1,"ttl":1065,"rdlength":4,"rdata_is_parsed":1,"rdata":"74.6.143.26"},{"name":"yahoo.com","type":1,"type_str":"A","class":1,"ttl":1065,"rdlength":4,"rdata_is_parsed":1,"rdata":"98.137.11.163"},{"name":"yahoo.com","type":1,"type_str":"A","class":1,"ttl":1065,"rdlength":4,"rdata_is_parsed":1,"rdata":"74.6.143.25"},{"name":"yahoo.com","type":1,"type_str":"A","class":1,"ttl":1065,"rdlength":4,"rdata_is_parsed":1,"rdata":"98.137.11.164"},{"name":"yahoo.com","type":1,"type_str":"A","class":1,"ttl":1065,"rdlength":4,"rdata_is_parsed":1,"rdata":"74.6.231.20"},{"name":"yahoo.com","type":1,"type_str":"A","class":1,"ttl":1065,"rdlength":4,"rdata_is_parsed":1,"rdata":"74.6.231.21"}],"dns_authorities":[],"dns_additionals":[],"dns_parse_err":0,"dns_unconsumed_bytes":0,"raw_data":"6ffa81800001000600000000057961686f6f03636f6d0000010001c00c000100010000042900044a068f1ac00c0001000100000429000462890ba3c00c000100010000042900044a068f19c00c0001000100000429000462890ba4c00c000100010000042900044a06e714c00c000100010000042900044a06e715","repeat":false,"cooldown":true,"timestamp_str":"2023-12-19T19:08:38.894+0000","timestamp_ts":1703012918,"timestamp_us":894721}
{"saddr":"1.1.1.1","saddr_raw":16843009,"daddr":"171.67.71.40","daddr_raw":675759019,"ipid":12105,"ttl":57,"sport":53,"dport":59553,"classification":"dns","success":true,"app_success":true,"udp_len":131,"dns_id":28666,"dns_rd":1,"dns_tc":0,"dns_aa":0,"dns_opcode":0,"dns_qr":1,"dns_rcode":0,"dns_cd":0,"dns_ad":0,"dns_z":0,"dns_ra":1,"dns_qdcount":1,"dns_ancount":6,"dns_nscount":0,"dns_arcount":0,"dns_questions":[{"name":"yahoo.com","qtype":1,"qtype_str":"A","qclass":1}],"dns_answers":[{"name":"yahoo.com","type":1,"type_str":"A","class":1,"ttl":1672,"rdlength":4,"rdata_is_parsed":1,"rdata":"74.6.143.25"},{"name":"yahoo.com","type":1,"type_str":"A","class":1,"ttl":1672,"rdlength":4,"rdata_is_parsed":1,"rdata":"74.6.231.21"},{"name":"yahoo.com","type":1,"type_str":"A","class":1,"ttl":1672,"rdlength":4,"rdata_is_parsed":1,"rdata":"98.137.11.163"},{"name":"yahoo.com","type":1,"type_str":"A","class":1,"ttl":1672,"rdlength":4,"rdata_is_parsed":1,"rdata":"74.6.143.26"},{"name":"yahoo.com","type":1,"type_str":"A","class":1,"ttl":1672,"rdlength":4,"rdata_is_parsed":1,"rdata":"98.137.11.164"},{"name":"yahoo.com","type":1,"type_str":"A","class":1,"ttl":1672,"rdlength":4,"rdata_is_parsed":1,"rdata":"74.6.231.20"}],"dns_authorities":[],"dns_additionals":[],"dns_parse_err":0,"dns_unconsumed_bytes":0,"raw_data":"6ffa81800001000600000000057961686f6f03636f6d0000010001c00c000100010000068800044a068f19c00c000100010000068800044a06e715c00c0001000100000688000462890ba3c00c000100010000068800044a068f1ac00c0001000100000688000462890ba4c00c000100010000068800044a06e714","repeat":true,"cooldown":true,"timestamp_str":"2023-12-19T19:08:38.895+0000","timestamp_ts":1703012918,"timestamp_us":895146}
```

### CODE REVIEW

File: src/probe_modules/module_dns.c [hunk 1]
```diff
@@ -87,7 +87,9 @@ static uint16_t *dns_packet_lens; // Not including udp header
 static uint16_t *qname_lens;
 static char **qnames;
 static uint16_t *qtypes;
-static int num_questions = 0;
+static int num_questions = 0; // How many DNS questions to query. Note: There's a requirement that the num_questions = probes input by user
+static char probe_arg_delimitor = ';';
```
Comment (zakird) [inline src/probe_modules/module_dns.c:91]: This can probably be `const`

**Comment by zakird** [comment]
I don't think that I'm fully parsing how this is supposed to work. I would expect `conf->packet_streams` to be set to a different value based on the description of the PR, but I don't actually see that logic anywhere (i.e., I don't see the number of probes sent ever changed by the probe module).

That said, I don't love the idea of probe modules changing global configuration — that seems very messy to me. I think it would make sure sense to instead throw a `log_fatal` and explain what the user needs to do. 

Last note, I could imagine that someone might want to send a _multiple_ of the number of probes (e.g., if there are two names, and you want to send a packet to each twice, then you set the number of probes to be 4).

File: src/probe_modules/module_dns.c [hunk 2]
```diff
@@ -87,7 +87,9 @@ static uint16_t *dns_packet_lens; // Not including udp header
...
+static void find_num_dns_questions(struct state_conf *);
```
Comment (zakird) [inline src/probe_modules/module_dns.c:92]: It doesn't really feel like this "finds the number of questions" given that it doesn't return any integer value for the number of questions.

Comment (phillip-stephens) [reply src/probe_modules/module_dns.c]: That's very fair, I've updated it!

File: src/probe_modules/module_dns.c [hunk 3]
```diff
@@ -1083,11 +1084,48 @@ probe_module_t module_dns = {
...
+		conf->probe_args = conf->probe_args + 1;
+	}
+	if (conf->probe_args[strlen(conf->probe_args) - 1] == probe_arg_delimitor) {
+		log_debug("dns", "Probe args (%s) contains trailing semicolon. Stripping.", conf->probe_args);
+		conf->probe_args[strlen(conf->probe_args) - 1] = '\n';
+	}
+	// find how many probe_args the user wants to query
+	if (conf->probe_args) {
+		int arg_strlen = strlen(conf->probe_args);
+		for (int i = 0; i < arg_strlen; i++) {
```
Comment (zakird) [inline src/probe_modules/module_dns.c:1125]: I think that the more canonical way to do this would be to use `strtok` or `strtok`. More broadly though, I do wonder if it makes sense that this is logic is different from the logic we use for actually _parsing out_ the questions. It seems that when parsing, we would know this information already and then wouldn't have this logic in different places.

**Review by zakird — APPROVED** [review]
Overall this seems fine, but personally, would have tried to have the string parsing logic in one place in the probe module instead of having counting in one place and parsing in another place such that both always have to be updated. There's a comment inline about this.

File: src/probe_modules/module_dns.c (hunk 3 above)
Comment (phillip-stephens) [reply src/probe_modules/module_dns.c]: Fair, and thanks for the suggestion to look at `stroke`, seems very much like the correct way to go about this. I've re-done the logic and it seems much cleaner. I've re-tested the scenarios I outlined in the PR, mind taking a second look and we can merge if it looks good to you? @zakird

Comment (phillip-stephens) [reply src/probe_modules/module_dns.c]: Update: let me integrate the changes made [here](https://github.com/zmap/zmap/pull/764), they'll conflict.

Comment (phillip-stephens) [reply src/probe_modules/module_dns.c]: I'll re-assign you when done.

File: src/probe_modules/module_dns.c [hunk 4]
```diff
@@ -88,10 +86,15 @@ static uint16_t *dns_packet_lens; // Not including udp header
...
+static int num_questions = 0; // How many DNS questions to query. Note: There's a requirement that probes is a multiple of DNS questions
+// necessary to null-terminate these since strtrk_r can take multiple delimitors as a char*, and since these are contiguous in memory,
+// they were being used jointly when the intention is to use only one at a time.
+static const char* probe_arg_delimitor = ";\0";
+static const char* domain_qtype_delimitor = ",\0";
+static const char* rn_delimitor = ":\0";
 
-const char *qopts_rn = "rn";
+static uint8_t *rdbits;
+const char *qopts_rn = "nr"; // used in query to disable recursion bit in DNS header
```
Comment (phillip-stephens) [inline src/probe_modules/module_dns.c:97]: Updated this, realized that we're using `nr` in the `--help` text, and I think it makes more sense as an abbreviation for `no recursion`

**Comment by phillip-stephens** [comment]
Ready for a re-review, logic is all in one place now @zakird

File: src/probe_modules/module_dns.c [hunk 5]
```diff
@@ -579,127 +581,118 @@ static bool process_response_answer(char **data, uint16_t *data_len,
...
-	char *qopts_str = NULL;
-	char **domains = (char **)xmalloc(sizeof(char *) * num_questions);
-
-	for (int i = 0; i < num_questions; i++) {
-		domains[i] = (char *)default_domain;
-		qtypes[i] = default_qtype;
-		rdbits[i] = default_rdbit;
+	if (conf->probe_args[strlen(conf->probe_args) - 1] == probe_arg_delimitor[0]) {
+		log_debug("dns", "Probe args (%s) contains trailing semicolon. Stripping.", conf->probe_args);
+		conf->probe_args[strlen(conf->probe_args) - 1] = '\n';
```
Comment (zakird) [inline src/probe_modules/module_dns.c:596]: This might be better as NULL byte

**Review by zakird — APPROVED** [review]
This looks sane, but I could 100% also have missed something here. Assuming that you have tested though and it works, LGTM to merge.
